### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by syafiqFiqq** [kmturley/cordova-open-fb#1]
im having trouble with implement your app. 
the app works like charm in android but it show security warning:please treat URL... 
do you know why this happens? and way to solve it..
i developed using hybrid app which is using ionic..
i view the app using the ionic view..
Thanks..

**Comment by kmturley** [comment]
Can you copy the actual error message here? It could be a few possible problems:
- try to not call the openFB.login() function too quickly, this caused me issues before
- make sure your facebook app configuration contains the correct urls

Check you have set it up correctly using my guide here:
http://kmturley.blogspot.com/2014/10/facebook-login-inside-hybrid-app-using.html

**Comment by syafiqFiqq** [comment]
http://prntscr.com/7hv8os
![screenshot_1](https://cloud.githubusercontent.com/assets/12907510/8198663/82aa4f88-14dc-11e5-8efa-f1b4d133809e.png)

this is the warning that i get.. i already follow your guide correctly on http://kmturley.blogspot.com/2014/10/facebook-login-inside-hybrid-app-using.html 

i even clone your project and redo all the step.. but it still display the warning..

your help much appreciate..
btw, thanks for the quick reply.. =)

**Comment by kmturley** [comment]
You are correct there was a problem, Facebook changed the following values:
- publish_stream > publish_actions
- fbtoken > fbAccessToken

I updated the openfb.js library which fixed those issues! Try checking the new version out now:
https://github.com/kmturley/cordova-open-fb
