### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by elshorbagy** [kmturley/cordova-open-fb#2]
Is this plugin still working with the new FB roles? I tried it and I got error that the url I'm redirecting the login page is not valid.

**Comment by kmturley** [comment]
Yes there is an error now when running inside android. seems to load fine in the browser. Will investigate!

**Comment by kmturley** [comment]
If you have Android Studio installed, when there is an error you can see the issue outputted in the logs. In this case I was getting two errors:

**Error 1**
07-03 09:18:37.637 3480-3480/io.cordova.hellocordova D/SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 312 : Error in Success callbackId: InAppBrowser1373123963 : ReferenceError: loginWindow_loadStopHandler is not defined

Looks like there is an error with openfb.js
https://github.com/ccoenraets/OpenFB/issues/78

This is the pull request to fix it:
https://github.com/ccoenraets/OpenFB/pull/73/commits

**Error 2**
07-03 09:23:55.052 3602-3626/io.cordova.hellocordova W/SystemWebViewClient: URL blocked by whitelist: https://graph.facebook.com/me?access_token=XXXXXX

The fix to this is to add the whitelist plugin:
```
cordova plugin add cordova-plugin-whitelist
cordova prepare
```

I've made the changes to the repo, including upgrading to the latest cordova:
https://github.com/kmturley/cordova-open-fb/commit/36cd8b9ee86f14ee7cbe78f16a219c88539e84e1
